# Generated by Django 4.2.13 on 2024-05-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
